name: 搜索节点订阅

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 */10 * *'

jobs:
  extract_urls:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4
          pip install requests
          pip install pyyaml
          pip install httpx
          
      - name: 延时
        run: |
          delay=$((RANDOM % 9 + 1))
          sleep "$delay"
          
      - name: 检查结果目录
        run: |         
          if [ ! -d "data" ]; then
            mkdir data
          fi
          if [ ! -d "share" ]; then
            mkdir share
          fi
          
      - name: 搜索订阅
        id: search
        run: python ./tools/extract_urls.py sec_urls
          
      - name: Remove duplicate URLs
        run: python ./tools/remove_duplicates.py sec_urls
        
      - name: Remove non-alphanumeric URLs
        run: python ./tools/remove_non_alphanumeric_urls.py sec_urls
      
      - name: 读取网页
        run: python ./tools/readweb.py sec_urls data --num_threads 20
      
      - name: 分析网页
        run: python ./tools/process_data.py data ./share/rest.txt rest_urls
        
      - name: Remove duplicate URLs
        run: python ./tools/remove_duplicates.py rest_urls
        
      - name: Remove non-alphanumeric URLs
        run: python ./tools/remove_non_alphanumeric_urls.py rest_urls
        
      - name: 读取订阅
        run: python ./tools/process_vpn.py rest_urls data 20 ./share/rest.txt 60
               
      - name: Remove non-alphanumeric vpn
        run: python ./tools/remove_non_alphanumeric_urls.py ./share/rest.txt
        
      - name: Remove duplicate vpn
        run: python ./tools/remove_duplicates.py ./share/rest.txt
        
      - name: 删除非特定链接
        run: python ./tools/filter_links.py ./share/rest.txt
        
      - name: Remove duplicate vpn
        run: python ./tools/base64_encode.py ./share/rest.txt ./share/encoded
        
      - name: 清除 data 目录
        run: |
          find data/ -type f -exec rm {} +

      - name: Display last run timestamp
        id: display_timestamp
        run: |
          echo "timestamp=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Update README with last run timestamp
        run: |
          echo "更新于：$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')" > README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md ./share/rest.txt ./share/encoded rest_urls sec_urls
          git commit -m "Update README with last run timestamp (${GITHUB_SHA})"
          git push
