name: 订阅

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 10,20,1 * *'

jobs:
  extract_urls:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4
          pip install requests
          pip install pyyaml
          
      - name: 检查结果目录
        run: |         
          if [ ! -d "data" ]; then
            mkdir data
          fi
          if [ ! -d "share" ]; then
            mkdir share
          fi
          
      - name: 搜索订阅
        id: search
        run: |
          declare -a search_queries=("节点订阅" "节点池2023" "VEMSS节点订阅")
          for query in "${search_queries[@]}"; do
            echo "Searching for: $query"
            python ./tools/extract_urls.py "$query"
          done
  
      - name: Remove duplicate URLs
        run: python ./tools/remove_duplicates.py sec_urls
        
      - name: Remove non-alphanumeric URLs
        run: python ./tools/remove_non_alphanumeric_urls.py sec_urls
      
      - name: 读取网页
        run: python ./tools/readweb.py sec_urls data 10
        
      - name: 分析网页
        run: python ./tools/process_data.py data rest_urls
        
      - name: 读取订阅
        run: python ./tools/readweb.py rest_urls data 10
        
      - name: 生成订阅
        run: python ./tools/process_vpn.py data ./share/rest.txt
        
      - name: Remove non-alphanumeric URLs
        run: python ./tools/remove_non_alphanumeric_urls.py ./share/rest.txt
        
      - name: Remove duplicate vpn
        run: python ./tools/remove_duplicates.py ./share/rest.txt
        
      - name: Remove duplicate vpn
        run: python ./tools/base64_encode.py ./share/rest.txt encoded
        
      - name: 清除 data 目录
        run: |
          find data/ -type f -exec rm {} +

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .

          # 检查工作树是否有更改
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Add extracted URLs"
            git pull --rebase origin master
            git push origin master
          else
            echo "No changes to commit. Skipping commit and push."
          fi
