name: 分析提取

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 10,20,1 * *'

jobs:
  extract_urls:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4
          pip install requests
          pip install pyyaml
          
      - name: 检查结果目录
        run: |         
          if [ ! -d "data" ]; then
            mkdir data
          fi
  
      - name: Remove duplicate URLs
        run: python ./tools/remove_duplicates.py sec_urls
        
      - name: Remove non-alphanumeric URLs
        run: python ./tools/remove_non_alphanumeric_urls.py sec_urls
      
      - name: Extract URLs
        run: python ./tools/readweb.py sec_urls data 10 rest_urls

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .

          # 检查工作树是否有更改
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Add extracted URLs"
            git push
          else
            echo "No changes to commit. Skipping commit and push."
          fi
