name: 测试

on:
  workflow_dispatch:

jobs:
  extract_urls:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4
          pip install requests
          pip install pyyaml
          pip install python-magic

      - name: 检查结果目录
        run: |
          if [ ! -d "data" ]; then
            mkdir data
          fi
          if [ ! -d "share" ]; then
            mkdir share
          fi

      - name: test
        run: python ./tools/remove_non_alphanumeric_urls.py rest_urls

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add extracted URLs"
          git push

      - name: Display last run timestamp
        id: display_timestamp
        run: echo "::set-output name=timestamp::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

      - name: Update README with last run timestamp
        uses: actions/github-script@v5
        with:
          script: |
            const fs = require('fs');
            let readmeContent = fs.readFileSync('README.md', 'utf8');
            const timestamp = '${{ steps.display_timestamp.outputs.timestamp }}';
            readmeContent = readmeContent.replace(/代码最后一次运行时间：.*/, `代码最后一次运行时间：${timestamp}`);
            fs.writeFileSync('README.md', readmeContent)
