name: 测试

on:
  workflow_dispatch:
  

jobs:
  extract_urls:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
          pip install beautifulsoup4
          pip install requests
          pip install pyyaml
          pip install python-magic
               
      - name: 检查结果目录
        run: |         
          if [ ! -d "data" ]; then
            mkdir data
          fi
          if [ ! -d "share" ]; then
            mkdir share
          fi
          
      - name: test
        id: search
        run: python ./tools/readweb.py sec_urls data 10
        
        #./tools/readweb.py sec_urls data 10
        #./tools/readweb.py rest_urls data 10
        #./tools/process_data.py data rest_urls
        #./tools/process_vpn.py data share ./share/rest.txt

      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add extracted URLs"
          git push
